# Data Science with the Spatially-enabled DataFrame

> Pandas is a data analysis and data engineering library that is very popular in the scientific Python ecosystem. The ArcGIS API for Python adds spatial capabilities to Pandas DataFrames through the Spatially Enabled DataFrame (SeDF). With the SeDF, you can not only manipulate your tabular data but also apply spatial algorithms and tools. This technical session takes you from the basics of Pandas and NumPy to the full suite of functions available with the SeDF, including visualizing data on a map and persisting the DataFrames as GIS files and web layers.

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

### Pandas 🐼

The giant panda (*Ailuropoda melanoleuca*), also known as the panda bear or simply panda, is a bear species endemic to China.

<img src="./panda.png" style="height:250px" />

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

#### While that may be true...

### Pandas (the 🐍 Python 🐍 library)

> Pandas (styled as `pandas`) is a software library written for the Python programming language for data manipulation and analysis. In particular, it offers data structures and operations for manipulating numerical tables and time series. The name is derived from the term "panel data", an econometrics term for data sets that include observations over multiple time periods for the same individuals, as well as a play on the phrase "Python data analysis". (From Wikipedia)

##### Pandas is a powerful data science library and provides the DataFrame implementation Esri (_the **API for Python** team_) has extended to provide robust **spatial** data support--more on that 🔜.

#### Key takeaways:
- Pandas is a package providing fast, flexible, and expressive data structures designed to make working with “relational” or “labeled” data both easy and intuitive
- Data feels like excel spreadsheets


#### Why use Pandas
- Easy handling of missing data
- Size mutability
- Automatic and explicit data alignment
- Powerful, flexible *group-by* functionality

#### Other Reasons
- Intelligent label-based slicing
- Fancy Indexing and subsetting
- Intuitive merging and joining data sets
- Flexible reshaping and pivoting of data sets

### NumPy

> NumPy (pronounced /ˈnʌmpaɪ/ NUM-py) is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. NumPy is open-source software and has many contributors. (From Wikipedia)

#### Key takeaways
- NumPy provides data structures (e.g high-performance arrays, multi-dimensional arrays) and functions that support managing (or generating/randomizing) large amounts of mathematical data.  
- NumPy data structures can be loaded into pandas data-structures

#### Let's get started!

In [1]:
# import pandas
# pandas is customarily imported as `pd`
import pandas as pd

# enable graphics output in notebook
%matplotlib inline

#### `pd.Series`

##### 1 dimensional labeled array
- Can hold any data type

`>>> s = pd.Series(data, index=index)`

##### Example: Creating a `Series`

In [4]:
# import numpy
# numpy is customarily imported as `np`
import numpy as np

# create some random data using numpy
random_data = np.random.randn(5)
random_data

array([ 0.28418964,  1.1009358 , -1.75150968, -1.66245981, -0.34683848])

In [5]:
# create the series from the numpy array generated above
series = pd.Series(random_data)
series

0    0.284190
1    1.100936
2   -1.751510
3   -1.662460
4   -0.346838
dtype: float64

This operation created a new Series, using the NumPy array as the source, and we can see the values matched to their index, along with the data type that was coerced from the input data, a 64-bit float.

#### pandas DataFrame

##### 2 dimensional labeled data structure with columns of varying type
much like a Excel spreadsheet or relational database table, e.g.:

<img src="./dataframe-basic.png" style="height:500px" />

In [6]:
# create a two dimensional array with the data
data = [
    [1, 2, 3], 
    [3, 4, None]
]
# define the columns (field mappings)
columns = ['A', 'B', 'C']

In [7]:
df = pd.DataFrame(data, columns=columns)
df

   A  B    C
0  1  2  3.0
1  3  4  NaN

#### Basic Data Import

Pandas provides built-in support for reading CSV data

In [22]:
iris_df = pd.read_csv("./iris.csv")

##### Peeking

- Display only a small portion of data to understand what you have
- You can look at the top and bottom of the data

In [23]:
iris_df.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth      Variety
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [24]:
iris_df.tail()

     SepalLength  SepalWidth  PetalLength  PetalWidth         Variety
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

In [25]:
# note this is the "shape" as in size of the dataset
# not spatially
iris_df.shape

(150, 5)

##### Slicing

Selecting by index values for various ranges can be provided

In [26]:
# index 23 to 33, every 3 records
iris_df[23:33:3]

    SepalLength  SepalWidth  PetalLength  PetalWidth      Variety
23          5.1         3.3          1.7         0.5  Iris-setosa
26          5.0         3.4          1.6         0.4  Iris-setosa
29          4.7         3.2          1.6         0.2  Iris-setosa
32          5.2         4.1          1.5         0.1  Iris-setosa

#### Describing Data

Get some baseline statistics for the dataset to help get an idea of its characteristics at a glance
- provides the standard deviation, min, max, and break down of values for numeric data

In [27]:
iris_df.describe()

       SepalLength  SepalWidth  PetalLength  PetalWidth
count   150.000000  150.000000   150.000000  150.000000
mean      5.843333    3.054000     3.758667    1.198667
std       0.828066    0.433594     1.764420    0.763161
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.350000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000

#### Shuffling Data

When data is loading in order it's a good practice to shuffle it up before sampling.
Here's one way to do it:

In [32]:
df = (iris_df
          # Return a random sample of items from an axis of object.
          .sample(frac=1)
          # Reset the index of the DataFrame, and use the default one instead.
          # Disassociates the new sample from the original order
          .reset_index(drop=True)
     )
df.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth         Variety
0          4.6         3.4          1.4         0.3     Iris-setosa
1          5.4         3.4          1.7         0.2     Iris-setosa
2          4.9         3.1          1.5         0.1     Iris-setosa
3          7.2         3.0          5.8         1.6  Iris-virginica
4          4.9         3.1          1.5         0.1     Iris-setosa

###### Method chaining / "Fluent" API

Notice the calls above.  Each of the called methods return a `DataFrame`, enabling calling other methods for further analysis.  Then, you can set the final result as the updated DataFrame to a new variable (or the original, if desired).

![cool](./cool.gif)

#### Columns

- DataFrames store information about the names and data types(dtypes)

In [34]:
# get the column definitions
df.columns

Index(['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth', 'Variety'], dtype='object')

In [35]:
# get the column definitions, together with their coerced type
df.dtypes

SepalLength    float64
SepalWidth     float64
PetalLength    float64
PetalWidth     float64
Variety         object
dtype: object

#### Accessing Data


- Zero based indexing (like most of Python)
  - Also supports negative indexing like Python list, where `-1` is the last item in the DataFrame
- Use `iloc` to access a row
- Use `['<column name>']` or `.ColumnName` to access a column

In [38]:
df.iloc[0]

SepalLength            4.6
SepalWidth             3.4
PetalLength            1.4
PetalWidth             0.3
Variety        Iris-setosa
Name: 0, dtype: object

In [43]:
type(df.iloc[0]) # Getting a single row is a Series!

pandas.core.series.Series

In [42]:
df.iloc[-1]

SepalLength            4.8
SepalWidth             3.0
PetalLength            1.4
PetalWidth             0.3
Variety        Iris-setosa
Name: 149, dtype: object

In [36]:
df.Variety

0          Iris-setosa
1          Iris-setosa
2          Iris-setosa
3       Iris-virginica
4          Iris-setosa
            ...
145     Iris-virginica
146        Iris-setosa
147        Iris-setosa
148    Iris-versicolor
149        Iris-setosa
Name: Variety, Length: 150, dtype: object

In [37]:
df['Variety']

0          Iris-setosa
1          Iris-setosa
2          Iris-setosa
3       Iris-virginica
4          Iris-setosa
            ...
145     Iris-virginica
146        Iris-setosa
147        Iris-setosa
148    Iris-versicolor
149        Iris-setosa
Name: Variety, Length: 150, dtype: object

In [45]:
type(df.Variety) # Getting a single column is also a Series!

pandas.core.series.Series

#### Selecting a subset of columns

In [47]:
iris_sepal_df = df[['SepalLength', 'SepalWidth', 'Variety']]
# This excludes petal data
iris_sepal_df.head()

   SepalLength  SepalWidth         Variety
0          4.6         3.4     Iris-setosa
1          5.4         3.4     Iris-setosa
2          4.9         3.1     Iris-setosa
3          7.2         3.0  Iris-virginica
4          4.9         3.1     Iris-setosa

#### Modifying schema and values

In [50]:
df_lower = (iris_sepal_df
            # str.lower is a function that takes in one parameter, 
            # the existing column is passed, and the result is saved as the new column name
                .rename(columns=str.lower)
                .assign(variety=lambda x: x['variety'].str.lower())
           )
df_lower.head()

   sepallength  sepalwidth         variety
0          4.6         3.4     iris-setosa
1          5.4         3.4     iris-setosa
2          4.9         3.1     iris-setosa
3          7.2         3.0  iris-virginica
4          4.9         3.1     iris-setosa

the columns are now lowercase, and the variety values are now lowercase

#### Working with Date/Time

In [51]:
dates_with_hour = [[12, 25,2025,10], [12,31,2025,11], [1,1,2026, 0]]
df = pd.DataFrame(dates_with_hour, columns=['month', 'day', 'year', 'hour'])
df

   month  day  year  hour
0     12   25  2025    10
1     12   31  2025    11
2      1    1  2026     0

In [52]:
df.dtypes

month    int64
day      int64
year     int64
hour     int64
dtype: object

In [54]:
# Let's add a new column that is typed according to this data
df['timestamp'] = pd.to_datetime(df)
df

   month  day  year  hour           timestamp
0     12   25  2025    10 2025-12-25 10:00:00
1     12   31  2025    11 2025-12-31 11:00:00
2      1    1  2026     0 2026-01-01 00:00:00

In [55]:
df.dtypes

month                 int64
day                   int64
year                  int64
hour                  int64
timestamp    datetime64[ns]
dtype: object

### Now let's build an index using the date

- Date/Time values can be used to index a DataFrame
- Helpful for time series data

In [56]:
dates_with_hour = [[12, 25,2025,10], [12,31,2025,11], [1,1,2026, 0]]
df = pd.DataFrame(dates_with_hour, columns=['month', 'day', 'year', 'hour'])
# create the index just with the date; drop the hour
df.index = pd.to_datetime(df[['month', 'day', 'year']])

In [60]:
# now that we have a datetime index, let's get the value for last Christmas
df.loc[pd.to_datetime('2025-12-25')]

month      12
day        25
year     2025
hour       10
Name: 2025-12-25 00:00:00, dtype: int64

#### Categorical Data
- Similar to domain values in Feature Classes
- used when you have a fixed number of values in a Series

In [64]:
import numpy as np
# create a DataFrame with 20 random integers between 0 and 100
df = pd.DataFrame({'value': np.random.randint(0, 100, 20)})
labels = [f"{i} - {i + 9}" for i in range(0, 100, 10)]
# Bin values into discrete intervals.
# Use cut when you need to segment and sort data values into bins. 
# This function is also useful for going from a continuous variable to a categorical variable.
# from pandas docs ^
df['group'] = pd.cut(df.value, range(0, 105, 10), right=False, labels=labels)
df.head()

   value    group
0     69  60 - 69
1     17  10 - 19
2     84  80 - 89
3     55  50 - 59
4     90  90 - 99

In [65]:
df.dtypes

value       int64
group    category
dtype: object

#### Load Categorical Data

Let's load some categorical data and apply the category at the same time:

In [66]:
structures = pd.read_csv('./structures.csv', dtype={'OCC_CLS' : 'category'})
structures.OCC_CLS.cat.categories

Index(['Agriculture', 'Assembly', 'Commercial', 'Education', 'Government',
       'Industrial', 'Residential', 'Utility and Misc'],
      dtype='object')

In [67]:
structures.head()

       OCC_CLS     SQFEET                   PROP_ADDR  PROP_CITY   E
0  Residential   461.5012                         NaN        NaN NaN
1  Residential   576.8832                         NaN        NaN NaN
2  Residential   395.5743                         NaN        NaN NaN
3  Residential  3626.1060  740 NORTH NORTHRIDGE DRIVE  BOUNTIFUL NaN
4  Residential   906.5269          342 NORTH 700 EAST  BOUNTIFUL NaN

In [68]:
structures.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OCC_CLS    2000 non-null   category
 1   SQFEET     2000 non-null   float64
 2   PROP_ADDR  1829 non-null   object
 3   PROP_CITY  1815 non-null   object
 4   E          0 non-null      float64
dtypes: category(1), float64(2), object(2)
memory usage: 64.9+ KB